name: Build And Publish To GHCR

on:
  push:
    branches:
      - "main"
env:
  IMAGE_NAME: ghcr.io/swisspong/hello-world-ghcr
jobs:
  build_publish_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push to GHCR
        run: |
          docker login --username swisspong --password=${{ secrets.GH_TOKEN }} ghcr.io
          docker build . -t ${{ env.IMAGE_NAME }}:latest
          docker push ${{env.IMAGE_NAME}}:latest
      - name: Run container
        run: |
          docker run ${{ env.IMAGE_NAME }}:latest
