name: ci

on:
  push:
    branches:
      - "main"
env:
  IMAGE_NAME: localhost:5000/hello-world/app
jobs:
  docker:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: Build and push to local registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
      - name: Inspect
        run: |
          docker buildx imagetools inspect ${{ env.IMAGE_NAME }}:latest
      - name: Run container
        run: docker run ${{ env.IMAGE_NAME }}:latest
